<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/igijon/ML_numpy_matplotlib_pandas/blob/main/0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

---

**Autor**: Inmaculada Gijón Cardos

**Licencia**: GPL v3 (https://www.gnu.org/licenses/gpl-3.0.html)

---

# NumPy

Nos proporciona tipos de datos que no están en Python y que se basan en los tipos básicos de Python.

> Nos proporciona arrays que no existen en Python, aunque sí existen las listas, diccionarios...

Nos proporciona arrays de N-dimensiones y funciones matemáticas sofisticadas. También mecanismos que nos facilitan tareas relacionadas con **álgebra lineal** y números **aleatorios**, por ejemplo.

In [1]:
import numpy as np

## Arrays
En numpy:
- **axis**: dimensión
- **rank**: número de dimensiones
- **shape**: lista de dimensiones con su longitud correspondiente
- **size**: número total de elementos (multiplicación de la longitud de las dimensiones)

In [3]:
# Array cuyos valores son todos 0
a = np.zeros((2, 4)) 
# Tendrá 2 filas y 4 columnas
# Tendrá dos axis, es decir, dos ejes, un axis por cada dimensión
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Lo que acabamos de hacer nos lo proporcionaría también dos listas anidadas de Python, pero tenemos muchas propiedades y funcionalidades que nos facilitan la vida

In [4]:
a.shape

(2, 4)

In [5]:
a.ndim

2

In [6]:
a.size

8

### Creación de arrays

In [7]:
# Array de tres dimensiones con valores 0
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
np.ones((2,3,4)) # Todo unos

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
# Array de dimesiones indicadas como primer argumento y valor indicado como segundo argumento
np.full((2, 3, 4), 6)

array([[[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]]])

Existe una función que nos permite inicializar nuestro array sin pasarle un valor concreto, lo inicializa con valores que tiene en memoria en ese momento, puede ser cualquier cosa que haya en disco, no es un valor aleatorio ni valores de 0.

In [10]:
# El valor de np.empty no es predecible
np.empty((2, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [15]:
# Inicialización de array utilizando lista de Python
array_from_list = np.array([1,2,3])

In [16]:
array_from_list

array([1, 2, 3])

In [17]:
array_from_list.ndim

1

In [21]:
array_from_list = np.array([[1, 2, 3], [4, 5, 7]])
array_from_list

array([[1, 2, 3],
       [4, 5, 7]])

In [22]:
array_from_list.ndim

2